sudo: required
language: node_js
node_js:
  - 'lts/*'

git:
  depth: 3

matrix:
  include:
    - os: linux
      env:
        - CHROME_BIN='/usr/bin/google-chrome'
        - DISPLAY=':99.0'
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
    - os: osx
      env: HOMEBREW_CASK_OPTS='--appdir=/Applications'

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update > /dev/null
      brew cask install google-chrome
    fi

install:
  - npm install

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sh -e /etc/init.d/xvfb start
    fi

script:
  - 'npm run test:e2e'
  # - 'npm run test:unit' # babel-jest with vue error
  - 'npm run build'
